import { createContext, useContext, useEffect, useState } from "react";
import { useHistory } from "react-router";
import { toast } from "react-toastify";
import api from "../../Services/api";

export const ProductsContext = createContext();

export const ProductsProvider = ({ children }) => {
  const history = useHistory();
  const [products, setProducts] = useState([
    {
      id: 1,
      title: "Ração Seca Nutrilus Pro Frango  Carne para Cães Adultos",
      description:
        "Ração para cachorro Premium Especial: Nutrição de alta qualidade pelo melhor custo benefício.",
      img: "https://www.petlove.com.br/images/products/250504/product/2492302_FRENTE.jpg?1635779700",
      price: 106.03,
      category: "ração",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 2,
      title: "Ração Seca True para Cães Adultos Raças Pequenas",
      description: "Ração Super Premium Natural para cães:",
      img: "https://www.petlove.com.br/images/products/237822/product/Ra%C3%A7%C3%A3o_Seca_True_para_C%C3%A3es_Adultos_Ra%C3%A7as_Pequenas_2638251.jpg?1627769277",
      price: 107.93,
      category: "ração",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 3,
      title:
        "Ração Seca Nutrilus Prime Frango para Cães Adultos de Raças Grandes",
      description:
        "Contém em sua composição extrato de yucca, que atua na redução de odor das fezes",
      img: "https://www.petlove.com.br/images/products/250927/product/2697120_Nutrilus-Prime-Ra%C3%A7as-Grandes.jpg?1636403498",
      price: 191.18,
      category: "ração",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 4,
      title:
        "Ração Premier Golden Formula Cães Adultos Frango e Arroz Mini Bits",
      description: "Saúde oral: auxilia a redução da formação do tártaro;",
      img: "https://www.petlove.com.br/images/products/210677/product/Ra%C3%A7%C3%A3o_Premier_Golden_Formula_C%C3%A3es_Adultos_Frango_e_Arroz_Mini_Bits_-_1_Kg_1213820_2.jpg?1627675581",
      price: 18.81,
      category: "ração",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 5,
      title: "Ração Premier Pet Formula Cães Adultos Raças Pequenas",
      description:
        "Saúde intestinal: através da combinação de ingredientes de alta digestibilidade, fibras especiais e prebiótico;",
      img: "https://www.petlove.com.br/images/products/223522/product/Ra%C3%A7%C3%A3o_Premier_Pet_Formula_C%C3%A3es_Adultos_Ra%C3%A7as_Pequenas_3108224_1KG.jpg?1627716313",
      price: 33.21,
      category: "ração",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 6,
      title:
        "Ração Royal Canin Canine Veterinary Diet Satiety Support para Cães Adultos",
      description:
        "Ajuda na manutenção da massa muscular durante o período de perda de peso;",
      img: "https://www.petlove.com.br/images/products/232530/product/Ra%C3%A7%C3%A3o_Royal_Canin_Canine_Veterinary_Diet_Satiety_Support_para_C%C3%A3es_Adultos_3102396-1.jpg?1627745771",
      price: 89.54,
      category: "ração",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 7,
      title:
        "Ração Seca Nestlé Purina Pro Plan Veterinary Diets UR St/0x para Trato Urinário de Cães",
      description: "Promove maior ingestão de água;",
      img: "https://www.petlove.com.br/images/products/227989/product/Ra%C3%A7%C3%A3o_Seca_Nestl%C3%A9_Purina_Pro_Plan_Veterinary_Diets_UR_St0x_para_Trato_Urin%C3%A1rio_de_C%C3%A3es_2542263.jpg?1627728826",
      price: 253.79,
      category: "ração",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 8,
      title: "Ração Úmida Pet Delícia Natural Caçarolinha de Carne",
      description:
        "Livre de conservantes, corantes, sabores artificiais, transgênicos e subprodutos",
      img: "https://www.petlove.com.br/images/products/249992/product/Ra%C3%A7%C3%A3o_%C3%9Amida_Pet_Del%C3%ADcia_Natural_Ca%C3%A7arolinha_de_Carne_-_110_g_1214635_%284%29.jpg?1635449865",
      price: 8.54,
      category: "ração",
      species: "dogs",
      userId: 1,
      bestSeller: true,
    },
    {
      id: 9,
      title: "Ração Úmida Pedigree Sachê Carne ao Molho para Cães Filhotes",
      description: "Balanço ideal de fibras",
      img: "https://www.petlove.com.br/images/products/241800/product/1193906_Ra%C3%A7%C3%A3o_%C3%9Amida_Pedigree_Sach%C3%AA_Carne_ao_Molho_para_C%C3%A3es_Filhotes_1.jpg?1627785545",
      price: 2.69,
      category: "ração",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 10,
      title:
        "Ração Úmida Pet Delícia Natural Risotinho de Frango Fácil Digestão",
      description:
        "Não contém carnes mecanicamente separada, altamente palatável e digestível",
      img: "https://www.petlove.com.br/images/products/250026/product/Ra%C3%A7%C3%A3o_%C3%9Amida_Pet_Del%C3%ADcia_Natural_Risotinho_de_Frango_F%C3%A1cil_Digest%C3%A3o_-_320_g_1214638_%285%29.jpg?1635450658",
      price: 14.39,
      category: "ração",
      species: "dogs",
      userId: 1,
      bestSeller: true,
    },
    {
      id: 11,
      title:
        "Ração Seca PremieR Pet Golden Salmão para Gatos Adultos Castrados",
      description: "Sabor inigualável: máxima satisfação para o paladar;",
      img: "https://www.petlove.com.br/images/products/213111/product/Ra%C3%A7%C3%A3o_Golden_Gatos_Adultos_Castrados_Salm%C3%A3o_31022435_1kg.jpg?1627684400",
      price: 25.11,
      category: "ração",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 12,
      title: "Ração Nestlé Purina Friskies Sachê Salmão ao Molho para Gatos",
      description: "Alimento úmido completo e balanceado;",
      img: "https://www.petlove.com.br/images/products/232255/product/Ra%C3%A7%C3%A3o_Nestl%C3%A9_Purina_Friskies_Sach%C3%AA_Salm%C3%A3o_ao_Molho_para_Gatos_3110439.jpg?1627744932",
      price: 2.42,
      category: "ração",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 13,
      title: "Ração Seca Nutrilus Pro Carne para Gatos Adultos Castrados",
      description:
        "Ração para gatos Premium Especial: Nutrição de alta qualidade pelo melhor custo benefício",
      img: "https://www.petlove.com.br/images/products/250519/product/2661130_FRENTE.jpg?1635791746",
      price: 118.99,
      category: "ração",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 14,
      title: "Ração Seca PremieR Pet Golden Gatos Adultos Castrados Carne",
      description: "- Sabor inigualável: máxima satisfação para o paladar;",
      img: "https://www.petlove.com.br/images/products/213099/product/Ra%C3%A7%C3%A3o_Golden_Gatos_Adultos_Castrados_Carne_3110240_1kg_lateral.jpg?1627684352",
      price: 24.21,
      category: "ração",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 15,
      title: "Ração GranPlus Salmão e Arroz para Gatos Castrados Adultos",
      description:
        "Satisfaz paladares exigentes, feito com ingredientes nobres cuidadosamente selecionados, que agradam aos paladares mais exigentes e garantem um bom aproveitamento de nutrientes para o organismo. ",
      img: "https://www.petlove.com.br/images/products/208238/product/Ra%C3%A7%C3%A3o_Affinity_PetCare_Gran_Plus_Salm%C3%A3o_e_Arroz_para_Gatos_Castrados_Adultos_3105842_3Kg.jpg?1627667589",
      price: 50.31,
      category: "ração",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 16,
      title: "Ração Faro Mix Sabor Peixe para Gatos Adultos",
      description: "Sabor peixe",
      img: "https://www.petlove.com.br/images/products/200269/product/Ra%C3%A7%C3%A3o_Affinity_Faro_Mix_Sabor_Peixe_para_Gatos_Adultos_-_1_Kg_1962247.jpg?1627643245",
      price: 18.81,
      category: "ração",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 17,
      title: "Ração GranPlus Carne e Arroz para Gatos Adultos",
      description:
        "Satisfaz paladares exigentes, feito com ingredientes nobres cuidadosamente selecionados, que agradam aos paladares mais exigentes e garantem um bom aproveitamento de nutrientes para o organismo",
      img: "https://www.petlove.com.br/images/products/208110/product/Ra%C3%A7%C3%A3o_Affinity_PetCare_Gran_Plus_Carne_e_Arroz_para_Gatos_Adultos_1746329_3Kg.jpg?1627667119",
      price: 50.31,
      category: "ração",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 18,
      title: "Ração Total Naturalis Frango e Peru para Gatos Castrados",
      description: "Menos calorias ideal para o controle do ganho de peso",
      img: "https://www.petlove.com.br/images/products/227768/product/Ra%C3%A7%C3%A3o_Total_Naturalis_Frango_e_Peru_para_Gatos_Castrados_3110270.jpg?1627728345",
      price: 20.69,
      category: "ração",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 19,
      title: "Ração Seca PremieR Pet Golden Seleção Natural para Gatos Adultos",
      description: "Sabor inigualável: máxima satisfação para o paladar;",
      img: "https://www.petlove.com.br/images/products/214707/product/Ra%C3%A7%C3%A3o_Golden_Premier_Pet_Sele%C3%A7%C3%A3o_Natural_para_Gatos_Adultos_3110245_1Kg_l.jpg?1627689154",
      price: 23.31,
      category: "ração",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 20,
      title:
        "Ração Royal Canin Exigent para Gatos Adultos com Paladar Exigente",
      description:
        "Ração super premium indicada para gatos adultos de 1 a 10 anos de idade, com apetite exigente e satisfaz completamente o apetite devido à sua palatabilidade superior.",
      img: "https://www.petlove.com.br/images/products/191248/product/20100202_-_FHN_EXIGENT_-_F.jpg?1627615905",
      price: 25.73,
      category: "ração",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 21,
      title: "Antipulgas e Carrapatos MSD Bravecto para Cães de 4,5 a 10 Kg",
      description:
        "Com ação rápida, promove o extermino total dos parasitas em 24 horas",
      img: "https://www.petlove.com.br/images/products/212200/product/Antipulgas_e_Carrapatos_MSD_Bravecto_para_C%C3%A3es_de_4_5_a_10_Kg_3104947-1_.jpg?1627681204",
      price: 173.35,
      category: "medicação",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 22,
      title: "Vermífugo Biovet Vermivet Composto 600 mg para Cães e Gatos",
      description: "- Previne contra infestações por vermes;",
      img: "https://www.petlove.com.br/images/products/223614/product/Verm%C3%ADfugo_Biovet_Vermivet_Composto_600_mg_para_C%C3%A3es_e_Gatos_31017917-1.jpg?1627716617",
      price: 9.45,
      category: "medicação",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 23,
      title: "Simparic para Cães de 5,1 a 10 Kg (20 mg) - Antipulgas",
      description: "Mata as pulgas antes que produzam ovos ",
      img: "https://www.petlove.com.br/images/products/191341/product/3110173.jpg?1627616192",
      price: 50.26,
      category: "medicação",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 24,
      title: "Suplemento Avert Ograx-3 1500 para Cães e Gatos",
      description:
        "Auxilia no controle da dor e minimiza reações inflamatórias crônicas",
      img: "https://www.petlove.com.br/images/products/190873/product/c%C3%B3pia1.jpg?1627615166",
      price: 135.9,
      category: "medicação",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 25,
      title: "Vermifugo Ceva Canex Composto para Cães",
      description: "É um vermífugo de uso oral",
      img: "https://www.petlove.com.br/images/products/182790/product/3128074.jpg?1627596077",
      price: 7.36,
      category: "medicação",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 26,
      title: "Suplemento Organnact Glicol Pet",
      description: " Estimula o apetite; ",
      img: "https://www.petlove.com.br/images/products/192036/product/glicol_pet_500ml_1651016_3_c%C3%B3pia.jpg?1627617620",
      price: 17.82,
      category: "medicação",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 27,
      title:
        "NexGard para Cães de 10,1 a 25 Kg (68 mg) - Antipulgas e Carrapatos",
      description: "Tablete mastigável sabor carne que os cães adoram",
      img: "https://www.petlove.com.br/images/products/227473/product/Antipulgas_e_Carrapatos_NexGard_68_mg_para_C%C3%A3es_de_10_1_a_25_Kg_3105747-1.jpg?1627727385",
      price: 78.27,
      category: "medicação",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 28,
      title: "Simparic para Cães de 20,1 a 40 Kg (80 mg) - Antipulgas",
      description:
        "Indicada para cães a partir de 8 semanas de idade e com acima de 1,3 Kg;",
      img: "https://www.petlove.com.br/images/products/191346/product/3110176.jpg?1627616214",
      price: 69.9,
      category: "medicação",
      species: "dogs",
      userId: 1,
      bestSeller: true,
    },
    {
      id: 29,
      title: "Suplemento Vetnil Probiótico para Cães e Gatos - 14 g",
      description: "Aditivo probiótico para cães e gatos.",
      img: "https://www.petlove.com.br/images/products/184501/product/31010527.jpg?1627599498",
      price: 36.81,
      category: "medicação",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 30,
      title: "Suplemento Vetnil Substituto do Leite Materno Pet Milk Sachê",
      description:
        "Possui taurina, aminoácido de grande importância na nutrição de felinos;",
      img: "https://www.petlove.com.br/images/products/195708/product/Suplemento_Vetnil_Substituto_do_Leite_Materno_Pet_Milk_Sach%C3%AA_-_100_g_1857504.jpg?1627627931",
      price: 46.11,
      category: "medicação",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 31,
      title: "Vermífugo Drontal Gatos 4 Kg - 4 Comprimidos",
      description: "Pode ser misturado a ração ou alimento;",
      img: "https://www.petlove.com.br/images/products/220050/product/Verm%C3%ADfugo_Drontal_Gatos_4_Kg_-_4_Comprimidos_310008.jpg?1627704856",
      price: 37.71,
      category: "medicação",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 32,
      title:
        "Combo Advocate Bayer para Gatos de 4 a 8 Kg (0,8 mL) - Antipulgas",
      description:
        "Indicado para o tratamento para o tratamento de sarnas: sarcóptica, demodécica e otodécica",
      img: "https://www.petlove.com.br/images/products/191970/product/ADVOCATE_COMBO_GATOS_8KG_%282%29.jpg?1627617471",
      price: 142.02,
      category: "medicação",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 33,
      title: "Vermífugo Helfine Plus para Gatos - 2 comprimidos",
      description:
        "Abrangendo os principais vermes redondos (nematódeos) e chatos (cestódeos).",
      img: "https://www.petlove.com.br/images/products/232938/product/Verm%C3%ADfugo_Helfine_Plus_para_Gatos_-_2_comprimidos_31019140.jpg?1627747064",
      price: 15.21,
      category: "medicação",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 34,
      title: "Vermífugo Biovet Vermivet 300 mg para Gatos",
      description: "Vermífugo Biovet Vermivet 300 mg para Gatos",
      img: "https://www.petlove.com.br/images/products/223615/product/Verm%C3%ADfugo_Biovet_Vermivet_300_mg_para_Gatos_31017920-1.jpg?1627716614",
      price: 16.76,
      category: "medicação",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 35,
      title: "Suplemento Organnact Promun Cat Pasta - 27 mL",
      description: "Fonte de energia;",
      img: "https://www.petlove.com.br/images/products/184846/product/3105969_2.JPG?1627600372",
      price: 32.58,
      category: "medicação",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 36,
      title: "Suplemento Vitamínico Avert Glicopet Felinus para Gatos",
      description:
        "Suplemento alimentar composto de glicose, vitaminas do complexo B, lisina, arginina e taurina;",
      img: "https://www.petlove.com.br/images/products/221084/product/Suplemento_Vitam%C3%ADnico_Avert_Glicopet_Felinus_para_Gatos_2481963.jpg?1627707569",
      price: 40.85,
      category: "medicação",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 37,
      title: "Suplemento Alivet P.P. Cat em Sachê - 10 g",
      description:
        " Previne e auxilia no tratamento de diarréias de origem bacteriana;",
      img: "https://www.petlove.com.br/images/products/6331/product/Suplemento_Alivet_P.P._Cat_em_Sach%C3%AA_-_10_g_3100419.jpg?1627500320",
      price: 10.71,
      category: "medicação",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 38,
      title: "Suplemento Vitamínico Organnact Promun Cat - 50 g",
      description:
        "Desempenha importante ação na manutenção do funcionamento cardíaco e na integridade da retina;",
      img: "https://www.petlove.com.br/images/products/221441/product/Suplemento_Vitam%C3%ADnico_Organnact_Promun_Cat_-_50_g_31014845.jpg?1627708903",
      price: 54.54,
      category: "medicação",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 39,
      title: "Feliway Classic Ceva",
      description:
        "Deve permanecer constantemente ligado na tomada do cômodo onde o gato passa a maior parte do tempo, por um período mínimo de 30 dias;Desenvolvido especialmente para gatos (Espécie-específico), é inodoro, não sedativo e não tem efeito sob outros animais ou pessoas",
      img: "https://www.petlove.com.br/images/products/192407/product/Feliway_Brasil_Aparelho_31018527-1_c%C3%B3pia.jpg?1627618533",
      price: 281.28,
      category: "medicação",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 40,
      title: "Organnact Cat Sbelt Diminuição de Peso dos Gatos",
      description: "Composto por mineral e aminoácido",
      img: "https://www.petlove.com.br/images/products/232410/product/Organnact_Cat_Sbelt_Diminui%C3%A7%C3%A3o_de_Peso_dos_Gatos_31023741.jpg?1627745396",
      price: 90.81,
      category: "medicação",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 41,
      title: "Aditivo Antiodor Kelco Pipicat Campestre",
      description: "Bandeja sempre seca e perfumada;",
      img: "https://www.petlove.com.br/images/products/229744/product/Aditivo_Antiodor_Kelco_Pipicat_Campestre_-_500_g_3101565.jpg?1627732084",
      price: 8.85,
      category: "hygiene",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 42,
      title: "Shampoo e Condicionador Pet Clean para Gatos",
      description:
        "2 em 1; pH Neutro; Com óleo de amêndoas; Pelos macios e hidratados. ",
      img: "https://www.petlove.com.br/images/products/249809/product/Shampoo_e_Condicionador_Pet_Clean_para_Gatos_-_700_mL_1979151_54.jpg?1635262884",
      price: 10.86,
      category: "hygiene",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 43,
      title: "Cortador de Unha Ferplast Gro 5808 para Gatos",
      description:
        "Cortador de unhas para gatos; Instrumento útil para cuidar das patas de seu amigo; Nova embalagem e empunhadura verde, específica para gatos;",
      img: "https://www.petlove.com.br/images/products/174458/product/Cortador-de-Unha-Ferplast-Gro-5808-para-Gatos.jpg?1627574227",
      price: 22.25,
      category: "hygiene",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 44,
      title: "Aditivo Antiodor Kelco Pipicat Antibacterial",
      description:
        "- Bandeja sempre seca; Inibe a proliferação de bactérias; Pode ser utilizado até 10 vezes. ",
      img: "https://www.petlove.com.br/images/products/229742/product/Aditivo_Antiodor_Kelco_Pipicat_Antibacterial_-_500_g_3101561.jpg?1627732068",
      price: 8.97,
      category: "hygiene",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 45,
      title: "Shampoo Procão Banho de Gato",
      description:
        "- pH balanceado; Limpa e hidrata sem agredir; Fragrância suave; Não irrita, não contém corantes.",
      img: "https://www.petlove.com.br/images/products/198551/product/Shampoo_Proc%C3%A3o_Banho_de_Gato_-_500_mL_1933620.jpg?1627637775",
      price: 16.11,
      category: "hygiene",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 46,
      title: "Rasqueadeira Ferplast Gro 5799 Carder para Gatos",
      description:
        "Escova para gatos; Ideal para animais com pelagem curta, média e longa; Nova embalagem e empunhadura verde, específica para gatos; Pontas arredondadas para serem delicadas e macias na pele de seu amigo. ",
      img: "https://www.petlove.com.br/images/products/174454/product/Rasqueadeira-Ferplast-Gro-5799-Carder-para-Gatos.jpg?1627574211",
      price: 29.45,
      category: "hygiene",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 47,
      title: "Shampoo Sanol Cat para Gatos - 500 mL",
      description: "Indicado para gatos; Sem corantes.",
      img: "https://www.petlove.com.br/images/products/224894/product/Shampoo_Sanol_Cat_para_Gatos_-_500_mL_31077040.jpg?1627721179",
      price: 14.08,
      category: "hygiene",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 48,
      title: "Kit Joy Vermelho para Gatos",
      description:
        "Fabricado com material de qualidade, indicado para gatos de todos os portes; Acompanha uma bandeja sanitária, um item indispensável para os felinos; Contém comedouro e uma pá higiênica super práticos; Espessura da pá higiênica é vazada e contribui para a economia da areia; Bordas laterais dá pá são mais alta, para melhor acomodação dos dejetos;",
      img: "https://www.petlove.com.br/images/products/247104/product/Kit_Joy_Vermelho_para_Gatos_2708720.jpg?1632943914",
      price: 34.61,
      category: "hygiene",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 49,
      title: "Shampoo Procão Cat Zone Miauuu para Gatos",
      description:
        "- Sem corantes; pH balanceado; Produto vegano; Não irrita a pele; Fórmula hidratante; Relaxa e tranquiliza. ",
      img: "https://www.petlove.com.br/images/products/234021/product/2626692_Shampoo_MIAUUU_.jpg?1627750668",
      price: 13.46,
      category: "hygiene",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 50,
      title: "Banho a Seco Bellogatto para Gatos",
      description:
        "- Higiene corporal sem necessidade de água; Ideal para os dias de temperaturas mais baixa; Elimina o mau cheiro, sem danificar a pele e os pelos; Abrilhanta os pelos do seu gato; Em spray para facilitar a aplicação. ",
      img: "https://www.petlove.com.br/images/products/195206/product/Banho_a_Seco_Bellogatto_para_Gatos_-_250_mL_3109824-1_1.jpg?1627626268",
      price: 33.05,
      category: "hygiene",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 51,
      title: "Neutralizador de Odor BelloGatto Extratos de Vegetais",
      description:
        " Neutraliza o odor de urina e fezes; Perfuma o ambiente, tornando o ar agradável; Ideal para lavagem de canis, gatis, quintais, áreas de serviços, clínicas veterinárias, etc. ",
      img: "",
      price: 37.35,
      category: "hygiene",
      species: "cats",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 52,
      title: "Tapete Higiênico Me.Au Pet Cheirinho Cítrico para Cães",
      description:
        "Tapete Higiênico Me.Au Pet Cheirinho Cítrico: Alegria em forma de produtos de qualidade, que te ajudam a economizar tempo e dinheiro.",
      img: "https://www.petlove.com.br/images/products/250538/product/2492322.jpg?1635797135",
      price: 53.48,
      category: "hygiene",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 53,
      title: "Tapete Higiênico Super Secão Citrus - 30 Unidades",
      description:
        "- Gel Absorvente; Atrativo Canino; Resistente a Ranhuras; Adesivo no Tapete; Abas Laterais; Vedação Especial; Agora com cheirinho de frutas cítricas",
      img: "https://www.petlove.com.br/images/products/141352/product/Tapete-Higi%C3%AAnico-Super-Sec%C3%A3o-Citrus---30-Unidades.jpg?1627518283",
      price: 71.91,
      category: "hygiene",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 54,
      title:
        "Sanitário Higiênico Weasy com Parede e Entrada de Água Bandeja Preta e Rosa Flamingo para Cães",
      description:
        "novador; Prático e higiênico; Maior durabilidade; Design moderno e bonito; Diminui o odor do ambiente; Opção ecológica que diminui a produção de lixo;",
      img: "https://www.petlove.com.br/images/products/234251/product/PRJAH_.jpg?1627751468",
      price: 569.9,
      category: "hygiene",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 55,
      title: "PS Care Eliminador de Odores Pet Society",
      description:
        "- Tira manchas; Pronto para uso; Limpa e higieniza; Limpador Multiuso; Ação em 10 segundos; Elimina maus odores;",
      img: "https://www.petlove.com.br/images/products/228038/product/PS_Care_Eliminador_de_Odores_Pet_Society_1932463.jpg?1627728985",
      price: 18.9,
      category: "hygiene",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 56,
      title: "Rasqueadeira The Pets Brasil com Cabo de Madeira",
      description:
        "Cabo em madeira; Evita nó e embaraços; Indicado para cães e gatos; Remove pelo morto indesejáveis; Estimula o crescimento de fios novos;  Cuidado com seu Pet na hora da limpeza",
      img: "https://www.petlove.com.br/images/products/237035/product/2649977_Rasqueadeira_The_Pets_Brasil_com_Cabo_de_Madeira_N1.jpg?1627761066",
      price: 11.69,
      category: "hygiene",
      species: "dogs",
      userId: 1,
      bestSeller: true,
    },
    {
      id: 57,
      title: "Shampoo Hidratante Bellokão Framboesa Premium",
      description: "- Fácil enxague; Ph balanceado; Shampoo Hidratante;",
      img: "https://www.petlove.com.br/images/products/237313/product/Shampoo_Hidratante_Bellok%C3%A3o_Framboesa_Premium__2653497_500ml.jpg?1627761971",
      price: 17.55,
      category: "hygiene",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 58,
      title: "Fonte Bebedouro Amicus Aqua Mini Bivolt Azul",
      description:
        " Fácil de limpar e montar; Em forma de torneira: oxigena e faz o pet beber mais água; - Indicada por Veterinários: ajuda a evitar problemas renais e urinários; - Bivolt Automática: só plugar em qualquer tomada 110V e 220V; - Baixa Tensão: com uma bomba mais segura, descarta o risco de acidentes;",
      img: "https://www.petlove.com.br/images/products/225532/product/Fonte_Bebedouro_Amicus_Aqua_Mini_Bivolt_Azul_1994059.jpg?1627723356",
      price: 78.08,
      category: "hygiene",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 59,
      title: "Lixeira Pipicão Suporte com Saquinhos Higiênicos Cata Caca Preto",
      description:
        "Prática e fácil de instalar; Indicado para cães e gatos; - Disponível em 40 e 50 litros; - Ideal para ambientes externos;- Possui suporte para saquinhos higiênicos",
      img: "https://www.petlove.com.br/images/products/237286/product/2653088_Lixeira_Pipic%C3%A3o_Suporte_com_Saquinhos_Higi%C3%AAnicos_Cata_Caca_Preto_40_1.jpg?1627761871",
      price: 278.55,
      category: "hygiene",
      species: "dogs",
      userId: 1,
      bestSeller: false,
    },
    {
      id: 60,
      title: "Seca Xixi Petmais Varrer Perfumado",
      description:
        "- Fácil de varrer; Evita o contato com a urina; Transforma o xixi do pet em pó; Ambiente higienizado com cheiro agradável",
      img: "https://www.petlove.com.br/images/products/195237/product/3107119.jpg?1627626382",
      price: 20.15,
      category: "hygiene",
      species: "dogs",
      userId: 1,
      bestSeller: true,
    },
    {
      id: 61,
      title: "Tapete Higiênico Pet Wash São Benedito Pet Lavável Vermelho",
      description:
        "Não vaza e não deixa cheiro;  Pode ser lavado todos os dias; Acabamento em viés.",
      img: "https://www.petlove.com.br/images/products/225333/product/1932523.jpg?1627722660",
      price: 19.71,
      category: "hygiene",
      species: "dogs",
      userId: 1,
      bestSeller: true,
    },
  ]);

  /* useEffect(() => {
    api.get("/products/").then((response) => setProducts(response.data));
  }, []); */

  return (
    <ProductsContext.Provider value={{ products, setProducts }}>
      {children}
    </ProductsContext.Provider>
  );
};

export const useProducts = () => useContext(ProductsContext);
